---
- name: OpenFace git repository
  git:
    repo: "{{ openface_mirror }}"
    dest: "{{ openface_download_dest }}"
    depth: 1
    update: no
    accept_hostkey: yes

- name: Set up for out of source build
  file:
    path: "{{ openface_download_dest }}/build"
    state: directory
    owner: "{{ ansible_user_id }}"

- name: CMake
  shell: "cmake -D CMAKE_BUILD_TYPE=RELEASE -D OpenCV_DIR:PATH={{ openface_opencv_dir }} .."
  args:
    chdir: "{{ openface_download_dest }}/build"
    executable: /bin/bash

- name: Make
  command: "make"
  args:
    chdir: "{{ openface_download_dest }}/build"

- name: Install
  command: "make install chdir={{ openface_download_dest }}/build"
  become: yes
  notify:
    - "finish install"
    - "clean up"